complete with succes

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -6,8 +6,12 @@ jobs:
     steps:
     - name: Run
       run: |
-        echo "Completed 'build' job, but triggering failure"
-        exit 1
+        echo "Run 'build' job"
+        
+    # - name: Complete with failure
+    #   run: |
+    #     echo "Completed 'build' job, but triggering failure"
+    #     exit 1
 
   notify:
     runs-on: ubuntu-latest
