fix 5

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -8,42 +8,43 @@ jobs:
       run: |
         echo "Run 'build' job"
         
-    # - name: Complete with failure
-    #   run: |
-    #     echo "Completed 'build' job, but triggering failure"
-    #     exit 1
+    - name: Complete with failure
+      run: |
+        echo "Completed 'build' job, but triggering failure"
+        exit 1
 
   notify:
     runs-on: ubuntu-latest
     if: ${{ always() }}
     needs: [build]
     env:
-      # WEBHOOK: https://discord.com/api/webhooks/1107328418640568370/KOm88HM1rPIJfBhQ7GP1RH_KZ4ke_4w0h1ZfKWNxTfbj32wP9QgeKFcKvm30Rpha1Lyv/github
       WEBHOOK: ${{ secrets.DISCORD }}
       AVATAR_URL: https://avatars.githubusercontent.com/u/29285980?s=400&u=e6644c135c541ef80b39bea82b09ffef175a2a52&v=4
+    
     steps:
     - name: Test Success
-      uses: rjstone/discord-webhook-notify@v1
-      # if: ${{ success() }}
       if: ${{ contains(needs.*.result, 'success') }}
+      uses: rjstone/discord-webhook-notify@v1
       with:
           severity: info
           details: Build Succeeded!
           webhookUrl: ${{ env.WEBHOOK }}
           avatarUrl: ${{ env.AVATAR_URL }}
+    
     - name: Test Failure
-      uses: rjstone/discord-webhook-notify@v1
-      # if: ${{ failure() }}
       if: ${{ contains(needs.*.result, 'failure') }}
+      uses: rjstone/discord-webhook-notify@v1
       with:
           severity: error
           details: Build Failed!
           webhookUrl: ${{ env.WEBHOOK }}
+          avatarUrl: ${{ env.AVATAR_URL }}
+
     - name: Test Cancelled
-      uses: rjstone/discord-webhook-notify@v1
-      # if: ${{ cancelled() }}
       if: ${{ contains(needs.*.result, 'cancelled') }}
+      uses: rjstone/discord-webhook-notify@v1
       with:
           severity: warn
           details: Build Cancelled!
           webhookUrl: ${{ env.WEBHOOK }}
+          avatarUrl: ${{ env.AVATAR_URL }}
